### ISSUE TITLE
Illegal relation name "published"

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-itu#25]
ITU references are using the relation name "published". This is not part of the relaton grammar:

````
DocRelationType =
    "obsoletes" |
    "obsoletedBy" |
    "supersedes" |
    "supersededBy" |
    "updates" |
    "updatedBy" |
    "complements" |
    "derivedFrom" |
    "translatedFrom" |
    "hasTranslation" |
    "adoptedFrom" |
    "equivalent" |
    "identical" |
    "nonequivalent" |
    "includedIn" |
    "includes" |
    "instance" |
    "instanceOf" |
    "partOf" |
    "hasPart" |
    "hasDraft" |
    "draftOf" |
    "merges" |
    "splits" |
    "amends" |
    "amendedBy" |
    "corrects" |
    "correctedBy" |
    "revises" |
    "revisedBy"
````

The relation needs to be one of these. I can't tell what is intended here at all; are these obsoletes? hasPart?

Please ensure all `relation/@type` are one of these; if they cannot be, we will need to update the grammar and its documentation.

**Comment by opoudjis** [comment]
From our documentation:

````
Generic Relations:

translatedFrom:: document A is a translation of document B
hasTranslation:: document A has a translation as document B
includedIn:: document A is included in document B, through a well-defined relation outlined in <<host-item>>, and with distinct metadata
includes:: document A includes document B, through a well-defined relation outlined in <<host-item>>, and with distinct metadata
hasPart:: document A includes document B, with no distinct metadata
partOf:: document A is included in document B, with no distinct metadata
complements:: document A is a complement or supplement of document B
derivedFrom:: document A is derived from document B
instance:: document A is an instance of document B (e.g. an edition, a format, a single copy)
instanceOf:: document A has as an instance document B (e.g. an edition, a format, a single copy)
hasDraft:: document A has as a draft document B
draftOf:: document A is a draft of document B
updates:: document A updates document B
updatedBy:: document A is updated by document B

Standards Relations:

obsoletes:: document A supersedes document B, and renders it obsolete
obsoletedBy:: document A is superseded by document B, and is rendered obsolete
supersedes:: document A supersedes document B, but is not rendered obsolete
supersededBy:: document A is superseded by document B, but is not rendered obsolete
adoptedFrom:: document A is adopted by a standards organisation from document B by a different organisation
identical:: document A is adopted from document B, without any change
equivalent:: document A is adopted from document B, without any significant textual change
nonequivalent:: document A is adopted from document B, and has been altered textually significantly
merges:: document A results from a merger of earlier documents B1, B2, B3...
splits:: document A is split off from earlier document B
corrects:: document A updates document B, and the change does not affect the intended meaning
correctedBy:: document A is updated by document B, and the change does not affect the intended meaning
amends:: document A updates document B, and the change is a minor change to the intended meaning
amendedBy:: document A is updated by document B, and the change is a minor change to the intended meaning
revised:: document A updates document B, and the change is a major change to the intended meaning
revisedBy:: document A is updated by document B, and the change is a major change to the intended meaning
````

**Comment by andrew2net** [comment]
@opoudjis @ronaldtse I don't remember why I make `published` default relation type. I'm not sure if a relation type could be scraped from the site. Do you see a relation type anywhere? Which type should we use as default?

**Comment by opoudjis** [comment]
Well, what are these related documents meant to be? I couldn't work that out.

**Comment by andrew2net** [comment]
@opoudjis this [document](https://www.itu.int/ITU-T/recommendations/rec.aspx?rec=13786&lang=en) has a tab named `Related supplement(s)`. Maybe the name of the tab means something?

**Comment by andrew2net** [comment]
Suppose we can use `amends` as a default relation type. @ronaldtse what do you think?

**Comment by ronaldtse** [comment]
@opoudjis which document in particular are we talking about? We need to talk about a particular instance to know whether the relation fits the two documents.

@andrew2net "Related Supplement" documents are clearly just "related" to the document, and fits none of the existing Relaton relationships. @opoudjis agree?

**Comment by opoudjis** [comment]
@ronaldtse Like Andrej has said, he's made it the default relation.

Related documents could be "complements", but if they're simply "related", yes, we should introduce a "related" relation. Can we confirm that is the case though with ITU? If they're just being mentioned on the ITU page as "see also"s, I'm not convinced they should be listed in the bibliographic entry at all.

**Comment by opoudjis** [comment]
@ronaldtse Please remove Appveyor from this repository (and any others).

**Comment by ronaldtse** [comment]
@opoudjis we don't have GitHub Actions setup for this yet. AppVeyor works in this repo. Please ticket the migration to GHA.

**Comment by ronaldtse** [comment]
> Can we confirm that is the case though with ITU? If they're just being mentioned on the ITU page as "see also"s, I'm not convinced they should be listed in the bibliographic entry at all.

I believe these documents are relevant to the "L series". This tab appears in all L series documents, such as L.102/L.26 (https://www.itu.int/ITU-T/recommendations/rec.aspx?rec=12533). 

The "related supplements" are "Supplements" to the "L series" of Recommendations; I'm not sure how they exactly relate to the particular document, but I will ask.

**Comment by ronaldtse** [comment]
From ITU:

> Supplements are informative documents described in ITU-T A.13. They are identified with a letter related to the series they belong to, plus a sequential number. 

> Supplements provide information that complement the one given in a Recommendation or a subseries or series of Recommendations. 

> The title of a Supplement may or not contain a Recommendation number.

Supplements can exist for:
- a single Recommendation
- a series of Recommendations
- a sub-series of Recommendations

From the description I propose the addition of a relation called `complements`. Thoughts?

**Comment by opoudjis** [comment]
We already have `complements`  as a document relation.

**Comment by ronaldtse** [comment]
Completely missed that. Let’s use `complements` in this case. @andrew2net

**Comment by andrew2net** [comment]
@ronaldtse ok, got it
