### ISSUE TITLE
Title contains redundant information

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-itu#26]
The gem is fetching the following as a title:

````
<title type="title-main" format="text/plain" language="en" script="Latn">ITU-T L.163 (11/2018): Criteria for optical cable installation with minimal existing infrastructure</title>
````

That is incorrect: the title is only _Criteria for optical cable installation with minimal existing infrastructure_.

The date needs to be stripped out of the title, and made the date of publication (`<date type="published">2018-11</date>`). We need the date, because it is included in ITU citations.

**Comment by opoudjis** [comment]
@andrew2net Nominally, we have till the end of the month to get ITU formatting right and reviewed by ITU; could you please action this within the next week?

**Comment by ronaldtse** [comment]
@andrew2net +1. Assigned.

**Comment by andrew2net** [comment]
> The date needs to be stripped out of the title, and made the date of publication (`<date type="published">2018-11</date>`). We need the date, because it is included in ITU citations.

@opoudjis it already gets `published` date form document's page `//table/tr/td/span[contains(@id, 'Label5')]`.

![image](https://user-images.githubusercontent.com/5623890/67149145-042d0e80-f2a8-11e9-8b51-1cbe5756aaf8.png)

**Comment by ronaldtse** [comment]
@andrew2net thanks for fixing the title. @opoudjis can you confirm this is fixed? Thanks.

**Comment by opoudjis** [comment]
Nope.

**Comment by opoudjis** [comment]
````
<p id="ITU-T_Y.3500" class="NormRef">[ITU-T Y.3500 (08/2014) | ISO/IEC  17788]&#xA0; Recommendation ITU-T Y.3500 (08/2014) | ISO/IEC  17788, <i>ITU-T Y.3500 (08/2014) | ISO/IEC  17788: Information technology &#x2013; Cloud computing &#x2013; Overview and vocabulary</i>.</p>
````

In that instance, we have a compound identifier still left as part of the title.

**Comment by andrew2net** [comment]
Fixed by https://github.com/relaton/relaton-itu/commit/af019a992d87c9043d521984d0694e6a1f1efcda
