### ISSUE TITLE
Identifier contains date

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-itu#27]
The document identifier contains the date:

````
<docidentifier type="ITU">ITU-T Y.3100 (09/2017)</docidentifier>
````

Documents in ITU are cited without the date. Could we please remove it from the document identifier?

**Comment by ronaldtse** [comment]
As seen in the following issue, the citation should contain year, but not the full date.

https://github.com/relaton/relaton-itu/issues/28#issuecomment-544234321

**Comment by opoudjis** [comment]
I've already taken care of the year citation. Does not affect this issue.

**Comment by ronaldtse** [comment]
Got it. Thanks.

**Comment by andrew2net** [comment]
Fixed by https://github.com/relaton/relaton-itu/commit/af019a992d87c9043d521984d0694e6a1f1efcda
