### ISSUE TITLE
Allow citation of ITU-T Supplements

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-itu#29]
ITU also has Recommendation Supplements, e.g. https://www.itu.int/ITU-T/recommendations/index_sg.aspx?sg=0

<img width="791" alt="Screen Shot 2019-10-23 at 10 17 15 PM" src="https://user-images.githubusercontent.com/11865/67402232-debf3e00-f5e2-11e9-91d0-ef5d43810a2c.png">

"ITU-T A Suppl. 2": https://www.itu.int/ITU-T/recommendations/rec.aspx?rec=5199

<img width="753" alt="Screen Shot 2019-10-23 at 10 17 52 PM" src="https://user-images.githubusercontent.com/11865/67402285-f5659500-f5e2-11e9-9d9c-df2608b28145.png">

**Comment by ronaldtse** [comment]
@andrew2net Thanks! Can you also help provide documentation on how to cite these items? I think Relaton.org for documentation is long overdue. (ping @strogonoff )

**Comment by andrew2net** [comment]
@ronaldtse do you mean update documentation on this [page](https://www.metanorma.com/author/topics/building/reference-lookup/)?
