### ISSUE TITLE
Relaton ITU should fetch `Supplements`

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-itu#31]
e.g. 
```
WARNING: no match found online for ITU-T G.Sup.47. The code must be exactly like it is on the standards website.
```

**Comment by andrew2net** [comment]
@ronaldtse  the reference should be `ITU-T G Suppl. 47`

**Comment by ronaldtse** [comment]
@andrew2net Is this syntax shown anywhere in our documentation? We need to maintain Relaton.org to show this.

Can you update the syntax in all documents of https://github.com/metanorma/mn-samples-itu ? 

I notice that ITU often uses "b-XXX_XXX" as reference -- This is clearly related to https://github.com/metanorma/metanorma-standoc/issues/159

**Comment by andrew2net** [comment]
> I notice that ITU often uses "b-XXX_XXX" as reference -- This is clearly related to [metanorma/metanorma-standoc#159](https://github.com/metanorma/metanorma-standoc/issues/159)

@ronaldtse `relaton-itu` can handle references lake "b-XXX_XXX" but `relaton` needs prefix "ITU" to recognize type of document.
