### ISSUE TITLE
Relaton update seems to freeze on ITU Z.100

### ISSUE THREAD

**Issue by opoudjis** [relaton/relaton-itu#34]
VCR cassette is obsolete in metanorma-itu. When I delete it and run spec, fetch of references consistently freezes while fetching ITU Z.100.

````
fetching IEC 60027...
fetching ISO 55000...
fetching GB 12663-2019...
fetching ISO/IEC 27001...
fetching ITU-T Z.100...
````

**Comment by ronaldtse** [comment]
@andrew2net do you have the commit that fixes this?

**Comment by andrew2net** [comment]
@ronaldtse There isn't to fix. It seems Nick had a network issue.

**Comment by ronaldtse** [comment]
@opoudjis can you confirm no fix was needed here?

**Comment by opoudjis** [comment]
Confirmed.
