### ISSUE TITLE
Relaton ITU index not working

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-itu#38]
In mn-samples-itu, the Relaton index is not showing any document, but all are built. Reproduced locally as well. Seems like a Relaton-ITU problem?

From: https://github.com/metanorma/mn-samples-itu/issues/94

**Comment by andrew2net** [comment]
@ronaldtse the document documents/Y.3507-201812.rxl has `series` without `title`:
```
<series type="tertiary">

</series>
```
but `title` is required in the the [grammar](https://github.com/relaton/relaton-models/blob/eaa416ba7c57ac5a4b54be22dbdde00727a026d6/grammars/biblio.rnc#L337)
```
series = element series {
  attribute type { SeriesType }?,
  (formattedref |
  (btitle, bplace?, seriesorganization?,
  abbreviation?,
  seriesfrom?, seriesto?,
  seriesnumber?, seriespartnumber?, seriesrun?))
}
```
so it caused an argument error. Is the document correct? Should we fix the document or don't create invalid `series` element?

**Comment by andrew2net** [comment]
Fixed. Please use relaton-bib v 1.0.3 and relaton-itu v 1.0.2

**Comment by ronaldtse** [comment]
Thanks, how did you resolve the issue?

**Comment by andrew2net** [comment]
> Thanks, how did you resolve the issue?

Don't create a `series` element if it doesn't contain `title` or `formattedref` element.
