### ISSUE TITLE
Fetch ITU-R from new search site

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-itu#42]
ITU-R now has a new search site for its contents:

* Recommendations: https://extranet.itu.int/brdocsearch/R-REC/
* Questions https://extranet.itu.int/brdocsearch/R-QUE/
* Reports https://extranet.itu.int/brdocsearch/R-REP/
* Handbooks https://extranet.itu.int/brdocsearch/R-HDB/
* Resolutions https://extranet.itu.int/brdocsearch/R-RES/Forms/Folders%20InForce.aspx

**Comment by ronaldtse** [comment]
This is apparently a SharePoint site, and it's tremendously slow. We should do a cache of this information in relaton-data-itu-r.

There are:
* 1172 Recommendations
* 194 Questions
* 599 Reports
* 42 Handbooks
* 40 Resolutions

I believe this scale would be possible.

**Comment by andrew2net** [comment]
@ronaldtse I believe we should create online cache service based on the `relaton` gem. The fetching steps could be:

- local relaton:
  - Check if the local relaton has valid document in it's cache.
  - If document doesn't exist then fetch it from online relaton service.
  - If the document exists then return it.
  - If document exists but outdated then try to fetch it from online relaton service.
  - If document is outdated but fetching from online relaton fails then returnd the outdated document.
- online relaton service:
  - Check if the online relaton service has valid document in it's cache.
  - If document doesn't then try to fetch it from a source using a flavor gem.
  - If the document exists then return it.
  - If document exists but outdated then try to fetch it from a source using a flavor gem.
  - If document is outdated but fetching from the source fails then returnd the outdated document.

I suggest to put the existed `relaton` gem with small changes into [AWS Lambda](https://aws.amazon.com/lambda/) container, so we get serverless online relaton cache service. We can use [AWS S3](https://aws.amazon.com/s3/) as a storage for the cached XML files.

**Comment by ronaldtse** [comment]
I agree, but I also believe we need something in between.

* relaton on git
  * store a cache of bibliographic information on git
  * every day use GHA to fetch updated information via the relaton gem
  * user can fetch individual items or the full collection of them through GitHub

I want us to first work on this Git repository, and use this Git repository to be the data storage basis of the Lambda endpoint. This Git repository could contain both YAML and XML, and can be served via GitHub Pages.

In particular, ITU has allowed us to explicitly cache and serve bibliographic information.

**Comment by andrew2net** [comment]
@ronaldtse does the [document](https://extranet.itu.int/brdocsearch/R-REC/Forms/ITU%20Recommendation%20Folder/docsethomepage.aspx?ID=19203&FolderCTID=0x0120D52000F22870A5AFA1054181BAD87677D647C400051FC5857030E848B2F8C42DB4271329&List=0661b581-2413-4e84-bab2-77e6db27af7f&RootFolder=%2Fbrdocsearch%2FR%2DREC%2FR%2DREC%2DRS%2FR%2DREC%2DRS%2E1745%2FR%2DREC%2DRS%2E1745%2D0%2D200603%2DI&RecSrc=%2Fbrdocsearch%2FR%2DREC%2FR%2DREC%2DRS%2FR%2DREC%2DRS%2E1745%2FR%2DREC%2DRS%2E1745%2D0%2D200603%2DI) has 2 nubers? "RS.1745" and "SA.1745". Sould we make 2 docidentifiers or 1?
![image](https://user-images.githubusercontent.com/5623890/103151463-92d7ce00-477e-11eb-8a98-b0ae1cc31e20.png)

**Comment by andrew2net** [comment]
@ronaldtse what dcoument type shoud questions and handbooks be? We have following options for ITU:
```
DocumentType =
"recommendation" | "recommendation-supplement" | "recommendation-amendment" | "recommendation-corrigendum" | "recommendation-errata" |
"recommendation-annex" | "focus-group" | "implementers-guide" | "technical-paper" | "technical-report" | "joint-itu-iso-iec" | "resolution" | "service-publication"
```
Suppose recommendations shoud be `recommendation`, reports be `technical-report`, and resolutions be `resolution`. Is it correct?

**Comment by ronaldtse** [comment]
Correct. Questions and handbooks should be new types: could you help update the Relaton ITU model for them?

**Comment by ronaldtse** [comment]
> @ronaldtse does the documenthave 2 numbers? "RS.1745" and "SA.1745". Should we make 2 docidentifiers or 1?

This should have 2 docidentifiers. There are other documents we have seen to have them, and some are cross-organization docidentifiers.
