### ISSUE TITLE
Verify `ITU-R TF.460-6` can be fetched

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-itu#43]
```
[relaton-itu] ("ITU-R TF.460-6") fetching...
Bibliography: Could not retrieve ITU-R TF.460-6: no access to online site
```

This is failing in Relaton-IEC 1.5. @andrew2net can you check that 1.7 works? Thanks.

**Comment by andrew2net** [comment]
@ronaldtse it works, but the document isn't available on https://www.itu.int/search

**Comment by ronaldtse** [comment]
@andrew2net the general search functionality works but not this particular document. Will open new issue.
