### ISSUE TITLE
Support new ITU-R Recommendation search interface

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-itu#45]
https://extranet.itu.int/brdocsearch/R-REC/

<img width="820" alt="Screen Shot 2020-12-09 at 2 00 52 AM" src="https://user-images.githubusercontent.com/11865/101522555-5f492580-39c2-11eb-9e8f-cc8c9f0e6227.png">

Recommendations filters:
<img width="193" alt="Screen Shot 2020-12-07 at 4 30 29 PM" src="https://user-images.githubusercontent.com/11865/101327349-86600400-38a9-11eb-80ee-3972fee26e4f.png">
<img width="160" alt="Screen Shot 2020-12-07 at 4 30 35 PM" src="https://user-images.githubusercontent.com/11865/101327361-895af480-38a9-11eb-9501-325ab0e2322b.png">

Radio category:
<img width="264" alt="Screen Shot 2020-12-07 at 4 30 53 PM" src="https://user-images.githubusercontent.com/11865/101327395-94158980-38a9-11eb-80be-adc502e4cda4.png">

<img width="369" alt="Screen Shot 2020-12-07 at 4 30 58 PM" src="https://user-images.githubusercontent.com/11865/101327400-97107a00-38a9-11eb-9d32-e1512f2f8f48.png">

Services:
<img width="193" alt="Screen Shot 2020-12-07 at 4 31 12 PM" src="https://user-images.githubusercontent.com/11865/101327425-9f68b500-38a9-11eb-9354-b7d63001727c.png">

<img width="220" alt="Screen Shot 2020-12-07 at 4 31 17 PM" src="https://user-images.githubusercontent.com/11865/101327432-a263a580-38a9-11eb-93d6-e4d907956962.png">
<img width="178" alt="Screen Shot 2020-12-07 at 4 31 24 PM" src="https://user-images.githubusercontent.com/11865/101327447-a68fc300-38a9-11eb-950f-4a6c01c67035.png">

Resp. WPs. (Responsible Working Parties)
<img width="172" alt="Screen Shot 2020-12-07 at 4 32 12 PM" src="https://user-images.githubusercontent.com/11865/101327514-c32bfb00-38a9-11eb-9d3a-7a43f6c9f31d.png">
<img width="191" alt="Screen Shot 2020-12-07 at 4 32 25 PM" src="https://user-images.githubusercontent.com/11865/101327541-cb843600-38a9-11eb-8008-70a62f4d7ccb.png">

Cross ref.
<img width="171" alt="Screen Shot 2020-12-07 at 4 32 43 PM" src="https://user-images.githubusercontent.com/11865/101327572-d5a63480-38a9-11eb-95c3-d6f898475d0a.png">

Approval date

<img width="214" alt="Screen Shot 2020-12-07 at 4 32 58 PM" src="https://user-images.githubusercontent.com/11865/101327614-dfc83300-38a9-11eb-9366-75a8e8a1c5ac.png">

**Comment by andrew2net** [comment]
We have all these documents in the relaton-data-itu-r repo
