### ISSUE TITLE
Support new ITU-R Questions search interface

### ISSUE THREAD

**Issue by ronaldtse** [relaton/relaton-itu#46]
https://extranet.itu.int/brdocsearch/R-QUE/Forms/folders_inforce.aspx

<img width="853" alt="Screen Shot 2020-12-09 at 2 01 29 AM" src="https://user-images.githubusercontent.com/11865/101522627-7556e600-39c2-11eb-93d4-a345f0332412.png">

Study groups
<img width="106" alt="Screen Shot 2020-12-09 at 1 40 03 AM" src="https://user-images.githubusercontent.com/11865/101520434-763a4880-39bf-11eb-87ae-7bb0b255a1a4.png">

Resp. WPs.
<img width="156" alt="Screen Shot 2020-12-09 at 1 40 27 AM" src="https://user-images.githubusercontent.com/11865/101520472-8520fb00-39bf-11eb-9011-3cec8b0405eb.png">

<img width="124" alt="Screen Shot 2020-12-09 at 1 40 37 AM" src="https://user-images.githubusercontent.com/11865/101520491-8b16dc00-39bf-11eb-9dab-ddf68860e1f0.png">

Approval date
<img width="200" alt="Screen Shot 2020-12-09 at 1 40 51 AM" src="https://user-images.githubusercontent.com/11865/101520516-9407ad80-39bf-11eb-8bbe-bc7b504b3fd3.png">

Target year
<img width="179" alt="Screen Shot 2020-12-09 at 1 41 02 AM" src="https://user-images.githubusercontent.com/11865/101520531-9a962500-39bf-11eb-8244-41e01c6e506c.png">

Category
<img width="183" alt="Screen Shot 2020-12-09 at 1 41 16 AM" src="https://user-images.githubusercontent.com/11865/101520554-a1bd3300-39bf-11eb-88b3-1cc4f8418850.png">

**Comment by andrew2net** [comment]
@ronaldtse since we have all the documents in the relato-data-itu-r repo we don't need to use the search interface.

**Comment by ronaldtse** [comment]
Excellent, thanks!
